### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by jvgonzalvo** [hugrubsan/Offline-Handwriting-Recognition-with-TensorFlow#2]
I followed the instructions on cleaning the dataset. When I try to run train.py, I got this:

```
2018-01-09 17:02:35.162139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.797
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.48GiB
2018-01-09 17:02:35.258151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 1 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.797
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 7.83GiB
2018-01-09 17:02:35.258803: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1 
2018-01-09 17:02:35.258813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y 
2018-01-09 17:02:35.258817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y 
2018-01-09 17:02:35.258824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
2018-01-09 17:02:35.258829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1070, pci bus id: 0000:02:00.0)
2018-01-09 17:02:39.336833: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.05GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-01-09 17:02:39.336918: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 87.29MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-01-09 17:02:49.337710: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.53GiB.  Current allocation summary follows.
2018-01-09 17:02:49.337800: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (256): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.337833: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (512): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.337866: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1024): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.337892: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2048): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.337915: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4096): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.337946: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8192): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.337977: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16384): 	Total Chunks: 1, Chunks in use: 0 29.2KiB allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338001: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (32768): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338043: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (65536): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338096: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (131072): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338120: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (262144): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338144: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (524288): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338168: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338195: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2097152): 	Total Chunks: 1, Chunks in use: 0 2.96MiB allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338220: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4194304): 	Total Chunks: 1, Chunks in use: 0 4.01MiB allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338243: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338267: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338291: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338315: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338342: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338368: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0 1.42GiB allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-01-09 17:02:49.338395: I tensorflow/core/common_runtime/bfc_allocator.cc:660] Bin for 1.53GiB was 256.00MiB, Chunk State: 
2018-01-09 17:02:49.338428: I tensorflow/core/common_runtime/bfc_allocator.cc:666]   Size: 1.42GiB | Requested Size: 0B | in_use: 0, prev:   Size: 625.00MiB | Requested Size: 625.00MiB | in_use: 1
2018-01-09 17:02:49.338452: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c00000 of size 1280
2018-01-09 17:02:49.338471: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c00500 of size 256
2018-01-09 17:02:49.338489: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c00600 of size 256
2018-01-09 17:02:49.338506: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c00700 of size 256
2018-01-09 17:02:49.338525: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c00800 of size 3328
2018-01-09 17:02:49.338542: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c01500 of size 256
2018-01-09 17:02:49.338558: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c01600 of size 3328
2018-01-09 17:02:49.338576: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c02300 of size 256
2018-01-09 17:02:49.338592: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c02400 of size 256
2018-01-09 17:02:49.338610: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c02500 of size 2048
2018-01-09 17:02:49.338627: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c02d00 of size 256
2018-01-09 17:02:49.338645: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c02e00 of size 100096
2018-01-09 17:02:49.338663: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c1b500 of size 256
2018-01-09 17:02:49.338681: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c1b600 of size 500224
2018-01-09 17:02:49.338698: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c95800 of size 512
2018-01-09 17:02:49.338714: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412c95a00 of size 2000128
2018-01-09 17:02:49.338732: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412e7df00 of size 1024
2018-01-09 17:02:49.338750: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10412e7e300 of size 8000000
2018-01-09 17:02:49.338767: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041361f500 of size 1792
2018-01-09 17:02:49.338785: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041361fc00 of size 320000
2018-01-09 17:02:49.338802: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041366de00 of size 1024
2018-01-09 17:02:49.338820: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041366e200 of size 50432
2018-01-09 17:02:49.338837: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041367a700 of size 256
2018-01-09 17:02:49.338855: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041367a800 of size 3200000
2018-01-09 17:02:49.338872: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413987c00 of size 3200000
2018-01-09 17:02:49.338889: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95000 of size 256
2018-01-09 17:02:49.338907: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95100 of size 256
2018-01-09 17:02:49.338924: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95200 of size 256
2018-01-09 17:02:49.338941: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95300 of size 512
2018-01-09 17:02:49.338958: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95500 of size 1024
2018-01-09 17:02:49.338975: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95900 of size 1024
2018-01-09 17:02:49.338993: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c95d00 of size 1792
2018-01-09 17:02:49.339010: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413c96400 of size 320000
2018-01-09 17:02:49.339027: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413ce4600 of size 50432
2018-01-09 17:02:49.339045: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413cf0b00 of size 256
2018-01-09 17:02:49.339062: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413cf0c00 of size 3200000
2018-01-09 17:02:49.339079: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10413ffe000 of size 3200000
2018-01-09 17:02:49.339096: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041430b400 of size 3200000
2018-01-09 17:02:49.339114: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1a800 of size 3328
2018-01-09 17:02:49.339132: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1b500 of size 256
2018-01-09 17:02:49.339149: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1b600 of size 256
2018-01-09 17:02:49.339166: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1b700 of size 256
2018-01-09 17:02:49.339183: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1b800 of size 256
2018-01-09 17:02:49.339200: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1b900 of size 3328
2018-01-09 17:02:49.339217: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1c600 of size 256
2018-01-09 17:02:49.339234: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1c700 of size 256
2018-01-09 17:02:49.339250: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1c800 of size 256
2018-01-09 17:02:49.339268: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1c900 of size 256
2018-01-09 17:02:49.339285: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1ca00 of size 256
2018-01-09 17:02:49.339302: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1cb00 of size 256
2018-01-09 17:02:49.339321: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1cc00 of size 256
2018-01-09 17:02:49.339339: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1cd00 of size 256
2018-01-09 17:02:49.339356: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1ce00 of size 256
2018-01-09 17:02:49.339373: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1cf00 of size 256
2018-01-09 17:02:49.339390: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1d000 of size 256
2018-01-09 17:02:49.339406: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1d100 of size 256
2018-01-09 17:02:49.339424: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a1d200 of size 10240
2018-01-09 17:02:49.339442: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a26f00 of size 40192
2018-01-09 17:02:49.339461: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414a30c00 of size 10240
2018-01-09 17:02:49.339478: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d28900 of size 3328
2018-01-09 17:02:49.339494: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d29600 of size 256
2018-01-09 17:02:49.339511: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d29700 of size 256
2018-01-09 17:02:49.339528: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d29800 of size 2048
2018-01-09 17:02:49.339545: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d2a000 of size 2048
2018-01-09 17:02:49.339561: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d2a800 of size 256
2018-01-09 17:02:49.339578: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d2a900 of size 256
2018-01-09 17:02:49.339595: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d2aa00 of size 100096
2018-01-09 17:02:49.339612: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d43100 of size 100096
2018-01-09 17:02:49.339629: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d5b800 of size 256
2018-01-09 17:02:49.339645: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d5b900 of size 256
2018-01-09 17:02:49.339663: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414d5ba00 of size 500224
2018-01-09 17:02:49.339681: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414dd5c00 of size 500224
2018-01-09 17:02:49.339697: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414e4fe00 of size 512
2018-01-09 17:02:49.339714: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414e50000 of size 512
2018-01-09 17:02:49.339731: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10414e50200 of size 2000128
2018-01-09 17:02:49.339748: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10415038700 of size 2000128
2018-01-09 17:02:49.339765: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10415220c00 of size 1024
2018-01-09 17:02:49.339782: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10415221000 of size 1024
2018-01-09 17:02:49.339799: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10415221400 of size 8000000
2018-01-09 17:02:49.339817: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x104159c2600 of size 8000000
2018-01-09 17:02:49.339834: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416163800 of size 1792
2018-01-09 17:02:49.339851: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416163f00 of size 1792
2018-01-09 17:02:49.339868: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416164600 of size 320000
2018-01-09 17:02:49.339885: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x104161b2800 of size 320000
2018-01-09 17:02:49.339903: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416200a00 of size 1024
2018-01-09 17:02:49.339919: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416200e00 of size 1024
2018-01-09 17:02:49.339936: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416201200 of size 50432
2018-01-09 17:02:49.339954: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041620d700 of size 50432
2018-01-09 17:02:49.339971: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416219c00 of size 256
2018-01-09 17:02:49.339988: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416219d00 of size 256
2018-01-09 17:02:49.340005: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416219e00 of size 3200000
2018-01-09 17:02:49.340023: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416527200 of size 3200000
2018-01-09 17:02:49.340040: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416834600 of size 3328
2018-01-09 17:02:49.340057: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416835300 of size 3328
2018-01-09 17:02:49.340074: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416836000 of size 3200000
2018-01-09 17:02:49.340092: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416b43400 of size 3200000
2018-01-09 17:02:49.340108: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416e50800 of size 3328
2018-01-09 17:02:49.340125: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416e51500 of size 3328
2018-01-09 17:02:49.340143: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416e52200 of size 2048
2018-01-09 17:02:49.340161: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416e52a00 of size 100096
2018-01-09 17:02:49.340178: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416e6b100 of size 500224
2018-01-09 17:02:49.340195: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10416ee5300 of size 2000128
2018-01-09 17:02:49.340212: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x104170cd800 of size 8000000
2018-01-09 17:02:49.340230: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041786ea00 of size 131072000
2018-01-09 17:02:49.340248: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041f56ea00 of size 2621440000
2018-01-09 17:02:49.340265: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x104bb96ea00 of size 655360000
2018-01-09 17:02:49.340283: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x104e2a6ea00 of size 655360000
2018-01-09 17:02:49.340300: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10509b6ea00 of size 655360000
2018-01-09 17:02:49.340317: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10530c6ea00 of size 655360000
2018-01-09 17:02:49.340334: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x10557d6ea00 of size 655360000
2018-01-09 17:02:49.340353: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x10414618800 of size 4202496
2018-01-09 17:02:49.340372: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x10414a1fa00 of size 29952
2018-01-09 17:02:49.340389: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x10414a33400 of size 3101952
2018-01-09 17:02:49.340407: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1057ee6ea00 of size 1525700096
2018-01-09 17:02:49.340424: I tensorflow/core/common_runtime/bfc_allocator.cc:693]      Summary of in-use Chunks by size: 
2018-01-09 17:02:49.340446: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 37 Chunks of size 256 totalling 9.2KiB
2018-01-09 17:02:49.340467: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 512 totalling 2.0KiB
2018-01-09 17:02:49.340487: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 8 Chunks of size 1024 totalling 8.0KiB
2018-01-09 17:02:49.340506: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
2018-01-09 17:02:49.340526: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 1792 totalling 7.0KiB
2018-01-09 17:02:49.340545: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 2048 totalling 8.0KiB
2018-01-09 17:02:49.340565: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 9 Chunks of size 3328 totalling 29.2KiB
2018-01-09 17:02:49.340586: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 10240 totalling 20.0KiB
2018-01-09 17:02:49.340607: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 40192 totalling 39.2KiB
2018-01-09 17:02:49.340626: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 50432 totalling 197.0KiB
2018-01-09 17:02:49.340647: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 100096 totalling 391.0KiB
2018-01-09 17:02:49.340667: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 320000 totalling 1.22MiB
2018-01-09 17:02:49.340686: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 500224 totalling 1.91MiB
2018-01-09 17:02:49.340705: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 2000128 totalling 7.63MiB
2018-01-09 17:02:49.340726: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 9 Chunks of size 3200000 totalling 27.47MiB
2018-01-09 17:02:49.340746: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 8000000 totalling 30.52MiB
2018-01-09 17:02:49.340767: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 131072000 totalling 125.00MiB
2018-01-09 17:02:49.340787: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 655360000 totalling 3.05GiB
2018-01-09 17:02:49.340807: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2621440000 totalling 2.44GiB
2018-01-09 17:02:49.340825: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 5.68GiB
2018-01-09 17:02:49.340889: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  7635156992
InUse:                  6102122496
MaxInUse:               7628157440
NumAllocs:                     133
MaxAllocSize:           4802500096

2018-01-09 17:02:49.340940: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *********************************************************************************___________________
2018-01-09 17:02:49.340979: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[500,32,512,50]
Traceback (most recent call last):
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[500,32,512,50]
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](dropout/mul, Variable_2/read)]]
	 [[Node: Reshape_2/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1840_Reshape_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 175, in <module>
    run_ctc()
  File "train.py", line 109, in run_ctc
    _ = session.run([optimizer], feed)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/kapitan/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[500,32,512,50]
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](dropout/mul, Variable_2/read)]]
	 [[Node: Reshape_2/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1840_Reshape_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Conv2D_1', defined at:
  File "train.py", line 175, in <module>
    run_ctc()
  File "train.py", line 73, in run_ctc
    num_conv5, num_rnn, num_fc, height, width, num_classes)
  File ".../ANN_model.py", line 90, in CNN_RNN_CTC
    h_conv2 = tf.nn.relu(tf.nn.conv2d(h_pool1, w_conv2, strides=[1,1,1,1], padding='SAME') + b_conv2)
  File .../tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File ".../tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File ".../tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File ".../tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[500,32,512,50]
	 [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](dropout/mul, Variable_2/read)]]
	 [[Node: Reshape_2/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1840_Reshape_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]](url)

```

**Comment by hugrubsan** [comment]
Try to reduce the  batch sizes or image dimensions in the configuration file.

Sorry for the delay.

**Comment by jvgonzalvo** [comment]
What are the specs of the machine you used to run training?

**Comment by hugrubsan** [comment]
The specifications are those that appear in the config. json file. I'll write them down here anyway:

- Number of filters CNN-1: 20
- Number of filters CNN-2: 50
- Number of filters CNN-3: 100
- Number of filters CNN-4: 200
- Number of filters CNN-1: 400
- Filter size: 5x5.
- Max-Pool Window: 2x2
- Dropout probability: 0.5
- Number of neurons RNNs: 200
- Number of neurons FeedForward: 200
- Number of labels: 63
- Sequence length for CTC: 32
- Batch Size: 500
- Image Size: 64x1024

If you have memory problems, I advise you to reduce batch size, image size, number of filters or number of neurons.

**Comment by jvgonzalvo** [comment]
I mean, what kind of GPUs did you use? How many GPUs did you use? What's the size of each GPU?

**Comment by hugrubsan** [comment]
Ohh, I'm sorry....

I used a Nvidia Tesla P100 16GB with single precision (float32) and a performance of 9.3 Teraflops.

**Comment by jvgonzalvo** [comment]
Ohhh, so that’s why. I’m using 2 8GB GTX 1070s

**Comment by hugrubsan** [comment]
That's why I'm telling you to reduce the dimensions, it should work that way.

**Comment by jvgonzalvo** [comment]
I tried it and it works. I’m actually trying it for my own [project](https://github.com/selcouthlyBlue/Tensorflow-OCR-Trainer) too now that uses Tensorflow’s Estimator, and it’s working as well although the performance is pretty bad. Thanks for the tip.

**Comment by jvgonzalvo** [comment]
How long did it take for you to train the model?

**Comment by hugrubsan** [comment]
Hi,

For the test proposed by the IAM Handwriting Database, with 4 or 5 hours
was enough, for validation takes days.

2018-02-20 8:58 GMT+01:00 Jerome <notifications@github.com>:

**Comment by hugrubsan** [comment]
I mean Cross-Validation.

2018-02-20 11:00 GMT+01:00 Hugo Rubio <hugrubsan@gmail.com>:

**Comment by jvgonzalvo** [comment]
I read your code and got confused about the meaning of epochs in it. If I recall correctly, 1 epoch = 1 pass over all the training examples. Meaning, it takes (number of training examples // batch size) steps to go through all the training data. So if there are 20000, epochs, won't that take too long? What does number of epochs mean in your code?
